# sample compose file for running graphite + grafana
version: '3'
services:
  no_logick:
    build:
      context: ./
    restart: always 
    image: "no_logick:latest"
    container_name: no_logick
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Moscow
      - FLASK_APP=/app/httpd2.py 
      - APP_SETTINGS=config.DevelopmentConfig      
      - DATABASE_URL=postgresql+psycopg2://skud:skud@172.16.0.7/skud
      - LANG='en_US.UTF-8'
      - LC_ALL='en_US.UTF-8'
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M

